# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  TestPipeline

resources:
- repo: self

variables:
  imageName: 'pipeline-Node-docker'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository:  mshahid1996/python_code_samples_network
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
